### ISSUE TITLE
Why to use the "old" azure-storage-blob 2.1.0 instead of the latest version ? 

### ISSUE THREAD

**Issue by vasica38** [microsoft/azfuse#2]
Why to use the "old" azure-storage-blob 2.1.0 instead of the latest version ?

**Comment by amsword** [comment]
when i built the lib a long time ago, I did not know there is a new SDK. So far, the old lib works well and there is no feature that can be only supported with the new lib. Thus, we do not do any migration, but it is welcome to send a PR to support both (make it back-compatible).
