### ISSUE TITLE
Implement actual FUSE

### ISSUE THREAD

**Issue by GuillaumeDesforges** [microsoft/azfuse#3]
Some Python packages rely on using compiled libraries which open files using the kernel API, not the Python one.
For instance, [openslide-python](https://openslide.org/api/python/) with 
```python
slide = openslide.OpenSlide("/path/to/file.svs")
```

The name "AzFuse" suggests that this _should_ be possible, as there is "FUSE" in the name.
I don't seem to see how to make it work.

My guess is that, today, this AzFuse provides a way to get a Python IO object which can be used as a file.
This means that it can be used by Python libraries which use standard IO methods on a Python IO object, but not libraries which rely on kernel FUSE.

Though it would be great that there is a FUSE implementation which uses AzCopy, which is said to have good performances.

**Comment by amsword** [comment]
Thanks for the suggestion. Currently, we name it with a term of fuse as the design principle mainly follows the idea of blobfuse. I agree that it would be great to have an implementation with the kernel fuse. We will think about this.
