### ISSUE TITLE
Question: Does azfuse support working with blobfuse mounts?

### ISSUE THREAD

**Issue by AvivAvital2** [microsoft/azfuse#5]
With the release of Blobfuse v2.0 there is a new config file (and possibly new backend).
Does azfuse support the new yaml configuration file?
Can it be used on a mounted blobfuse v2.x directory?

Thanks

**Comment by amsword** [comment]
Does azfuse support the new yaml configuration file?
do you mean whether azfuse supports the configuration file of blobfuse2? If so, no.

Can it be used on a mounted blobfuse v2.x directory?
If the local path in azfuse is pointing a mounted blobfuse directory, it is fine as 'local path' is more like a logic path. azfuse won't try to access any data in the real path as it will download the data from 'remote path' to 'cache path' and open the file in 'cache path'.
